apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: service-list-role
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-list-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: api-call
    namespace: t23
roleRef:
  kind: ClusterRole
  name: service-list-role
  apiGroup: rbac.authorization.k8s.io